---
#  Reboot and wait for system to come online
#
#  Outline:
#    1.  Reboot RHEL Guest
#    2.  Wait for reboot to complete
#
#  Note:  This playbook is for Ansible v2.7 or later where the reboot module exists
#
- name: Reboot host and wait for it to come back online
  hosts: all
  gather_facts: no
  become: yes
 
  tasks:
    - name: Reboot the system using the reboot modules (found in Ansible v2.7 or later)
      reboot:
        msg: Automated reboot initiated via Ansible Tower automation
        post_reboot_delay: 25
        reboot_timeout: 200

    - name: Invoke Ping module on the host to verify that it is up
      ping:
...