---
#  Reboot and wait for system to come online
#
#  Outline:
#    1.  Reboot RHEL Guest
#    2.  Wait for reboot to complete
#
#  Note:  This can all be done with the reboot module in Ansible 2.7 within a single task.  This shows the
#         method prior to the reboot module
#
- name: Reboot host and wait for it to come back online
  hosts: all
  gather_facts: no
  become: yes
 
  tasks:
    - name: Restart the system
      shell: sleep 2 && shutdown -r now "Reboot post patching via Ansible"
      async: 1
      poll: 0
      ignore_errors: true

    - name: Wait for the server to resume operation
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 22
        state: started
        delay: 25
        timeout: 200
      become: false
      delegate_to: localhost

    - name: Invoke Ping module on the host to verify that it is up
      ping:
...