---
#  Get the RHEL born on date
#
- name: View RHEL born on date
  hosts: all
  # remote_user: ansibleop
  become: yes

  tasks:
    - name: Query the RHEL born on date
      shell:  "rpm -qi basesystem | grep '^Install Date'"
      register: bornOnDate
      
    - name: Display the born on date
      debug:
        var: bornOnDate.stdout
      
...
