---
- name: Unregister hosts from RHSM
  hosts: all:!sat*.lab.local
  tasks:
    - name: run the command to unregister the system
      command: 'subscription-manager --unregister'
      
    - name: run the command to clean the local data
      command: 'subscription-manager --clean'
