---
#  Example of setting the timezone
#
#  Outline:
#    1.  Build a new system via Kickstart.  I don't set the timezone in my kickstarts,
#        do all the boxes come in UTC
#    2.  Use the timezone module to set the TZ to America/Chicago
#
- name: Set the timezone to America/Chicago

  hosts: all
  remote_user: ansibleop
  become: yes

  tasks:
    - name: Set the default timezone to America/Chicago
      timezone:
        name:  "America/Chicago"
...